### ISSUE TITLE
Remove CRT

### ISSUE THREAD

**Issue by StrangeZak** [StrangeZak/Handmade-Math#16]
Remove use of the CRT (Math.h) in HandmadeMath, this involved replacing Sin, Con, and Tan with our own version of these operations.

**Comment by kiljacken** [comment]
Just sharing my $0.02 again here, such that they're documented somewhere.

The trigonometric functions are, to say the least, problematic to implement. You can basically pick one of the following options: widely compatible or fast. As you'd not want to maintain platform dependent inline assembly for all used architectures, platforms, and compilers, the slow route would have to be taken.

However, a possible solution could be the STB style of function definitions, allowing the user of Handmade-Math to pass in their own Sin/Cos/Tan and fallback to math.h if no such functions are provided.

**Comment by StrangeZak** [comment]
Yeah, writing SSE efficient Sin, Cos, and Tan will be crazy hard and will take more time then they are probably worth.

**Comment by StrangeZak** [comment]
I think the STB approach you are saying might be the way to go about these things.

**Comment by StrangeZak** [comment]
@kiljacken I did what you said in 0.4 the most recent commit, that i pushed today onto the master repo. It worked great :)
