### ISSUE TITLE
Functions without prototypes and prototypes without functions

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#20]
There are many function prototypes in the `HANDMADE_MATH_CPP_MODE` headers that do not have function bodies. (These start on [line 379](https://github.com/StrangeZak/Handmade-Math/blob/master/HandmadeMath.h#L379) at the time of this issue.) Further, most of these function prototypes don't make any sense:

```
HMMDEF hmm_vec4 HMM_Add(int X, int Y, int Z, int W);
```

What is that even supposed to do?

There are also lots of functions in the `HANDMADE_MATH_CPP_MODE` implementations that do not have associated prototypes, so they are uncallable except by the file that defines `HANDMADE_MATH_IMPLEMENTATION`:

```
HINLINE hmm_vec2
Add(hmm_vec2 Left, hmm_vec2 Right)
{
    hmm_vec2 Result = HMM_AddVec2(Left, Right);

    return (Result);
}
```

I suspect that these two problems are related, since I see that version 2.0 was supposed to prefix all functions, but presumably missed these.

------------------

I suspect that the desired behavior was as follows:

- Provide C-compatible headers like `HMM_AddVec4` for each function (since C does not support function overloading)
- For C++ mode, provide overloaded functions like `HMM_Add` so that code can be more concise.
- For C++ mode, provide operator overloading so that code can be mathy!

If those assumptions are correct, I'd be happy to get going on a fix for this.

**Comment by StrangeZak** [comment]
Yes! HandmadeMath should work like the stb libraries where the top part outside of the HANDMADE_MATH_IMPLEMENTATION should like a header or *.h file. I obviously must've missed some such as HMM_AddVec4, and yes the function overloaded and operator overloaded functions should work as you defined. If you can do this fix that would be awesome, thanks for finding this "bug" if you have another questions just let me know.

_PS: Be sure to keep the style i have already defined throughout the whole library ;)_

**Comment by bvisness** [comment]
@StrangeZak Could you please look at [this diff](https://github.com/bvisness/Handmade-Math/commit/99bad6fd6ebb977110abed02b5e6e910f800b9f7) and tell me if those are the changes you expected?

**Comment by StrangeZak** [comment]
@bvisness Commented on the diff for what im looking for
