### ISSUE TITLE
Needs unit testing

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#21]
Just wanted to open up the discussion about how unit testing should be implemented for Handmade Math. We could use a full C++ unit testing framework like [Google Test](https://github.com/google/googletest), or maybe just roll our own thing with asserts.

I personally would lean toward a full framework for ease of running multiple tests and nice test output. Plus, it would likely be easier to get up and running with Travis CI or some other automated tool, if we decide to go that route.

**Comment by StrangeZak** [comment]
I think for right now just having our own unit thing right now would be fine as i really dont have the money to setup a Travis of Jenkins server for automated build tests. Although i do think Travis or Jenkins would be the way to go for this.

**Comment by StrangeZak** [comment]
Wait is Travis CL free now ?

**Comment by bvisness** [comment]
Travis CI is [free for open-source projects](https://travis-ci.com/plans), and I'd be happy to set it up once we get tests running locally. I think later today I will take a stab at using Google Test and will let you know how it goes.

**Comment by kiljacken** [comment]
Travis is free for open source (maybe just github) projects afaik.

**Comment by StrangeZak** [comment]
Yeah, im not really the guy to ask to write a unit test. So if any of you guys are good at it i would love if you could try to do it first, once we have that id be more than happy to setup Travis CL, because we really need a unit test, so were sure we dont break peoples code when we upgrade, heh.

**Comment by StrangeZak** [comment]
@kiljacken @bvisness Someone is having a issue with handmade-math theres no reason they should have to transpose there matrices when submitting them to opengl right?

**Comment by bvisness** [comment]
Making some good headway on this! If you are interested you can check out the `unit-tests` branch of [my fork](https://github.com/bvisness/Handmade-Math).

**Comment by StrangeZak** [comment]
I do all my builds on Windows as a build.bat files so eventually ill just convert the make file to batch script but random question what are we gaining by using the google api thing

**Comment by bvisness** [comment]
We're gaining easy-to-create tests where individual asserts won't end the program, and very helpful formatting to help track down the source of errors. (Plus, it's a format that Travis should be happy with.)

Example output:

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Initialization
[ RUN      ] Initialization.Vectors
../test/hmm_test.cpp:34: Failure
      Expected: v3i.Elements[2]
      Which is: 3
To be equal to: 4.0f
      Which is: 4
[  FAILED  ] Initialization.Vectors (1 ms)
[----------] 1 test from Initialization (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Initialization.Vectors
```

**Comment by StrangeZak** [comment]
Awesome just didn't wanna bloat the project with a library, we didn't need but this seems fine as it won't even be used in HandmadeMath

**Comment by bvisness** [comment]
Yeah for sure. Maybe someone can make a handmade test framework for us :)

**Comment by StrangeZak** [comment]
Or, that could be a awesome side-project for us to work on when HandmadeMath is stable and faster than GLM

**Comment by StrangeZak** [comment]
Whats the status on the unit test ?

**Comment by bvisness** [comment]
1300 lines later, almost done writing them. Found a couple confirmed bugs and a few other issues (which I will make Github issues for.) Just have to write tests for `HMM_Orthographic`, `HMM_Projection`, and `HMM_LookAt` and we'll be good to go.

**Comment by bvisness** [comment]
(The tests are a little verbose in spots, but I'm just cranking them out and I can look into removing redundant code once everything works.)

**Comment by StrangeZak** [comment]
Awesome were finding bugs this is great :D After some testing of the next major version i thing we can finally call this "stable"

**Comment by StrangeZak** [comment]
Cant wait to squash these bugs

**Comment by bvisness** [comment]
I'll try to finish up the tests tonight.

**Comment by StrangeZak** [comment]
Thanks for writing the unit test :)

**Comment by bvisness** [comment]
Tests are up! Sadly it looks like there are some merge conflicts that will need resolving, but they shouldn't be too bad since most of the changes are new code anyway.

I'm going to go through and make issues for the stuff I found along the way. Once those are resolved I can try configuring Travis.

**Comment by StrangeZak** [comment]
Awesome, with LOTS of bugs found now and a unit test i think we on to a proper version 1.0

**Comment by StrangeZak** [comment]
Ill squash out a few of these bugs this after noon after i get ready, a lot of these seem like easy fixes i can do in an hour or two. So you can focus on just getting the unit tests to merge in.

**Comment by bvisness** [comment]
I'll merge and re-push so that conflicts will be resolved.

**Comment by StrangeZak** [comment]
Im writing a quick opengl visual test bed right now we can run some tests against also
