### ISSUE TITLE
Smooth Transition for GLM to Handmade Math

### ISSUE THREAD

**Issue by StrangeZak** [StrangeZak/Handmade-Math#22]
@kiljacken @bvisness Someone is having a issue with handmade-math there's no reason they should have to transpose there matrices when submitting them to OpenGL right? It seem like the transition from GLM to Handmade Math is not as easy as i thought it was.

Here's the Twitter thread to that kinda explains whats going on, on his side, this shows the complete conversation: https://twitter.com/JesseRMeyer/status/768281652682366976

Anyone have any idea whats going on?

**Comment by JesseRMeyer** [comment]
That's me. I used HMM as a 'drop-in' replacement for GLM, and in order to do any basic translations I had to transpose HMM's matrices to GL. More advanced use of matrices (projection, view, rotation) was completely unusable, causing the transformed points to fall outside of GL's frustum and be culled away. I can provide example source.

**Comment by bvisness** [comment]
I think we might be inconsistent about row-major vs. column-major order right now (GLM is column-major.) I'm looking into it.

**Comment by StrangeZak** [comment]
I mean i dont transpose any of my matrices and im fine, but if there is a issue we should fix it and have it so matrices do not need to be transposed, no reason for opengl to do that extra work

**Comment by bvisness** [comment]
@StrangeZak What's your source for the perspective projection matrix? I don't have a linear algebra textbook handy and Google is being no help...

**Comment by StrangeZak** [comment]
One second let me look i dont remember where i got it, but i can you reassure you it works.

**Comment by StrangeZak** [comment]
Maybe these two videos:

https://www.youtube.com/watch?v=jeO_ytN_0kk
https://www.youtube.com/watch?v=dul0mui292Q

If you wanna check it that would be awesome.

**Comment by bvisness** [comment]
@JesseRMeyer `HMM_Translate` is producing a row-major matrix instead of column-major (which OpenGL expects.) The rest of the functions seem to be producing column-major.

I hadn't run into this problem in my own project because I'm not yet using `HMM_Translate`. I'm starting work on a patch.

@StrangeZak Is your project using `HMM_Translate` at all? I'm surprised it would work for you...

(Also, this just highlights the need for #21!)

**Comment by StrangeZak** [comment]
I think i might just use HMM_LookAt for the time being maybe thats why mine works, yeah we really need a Unit Test obviously. How has no body else hit this with so many people using it

**Comment by StrangeZak** [comment]
There's like 25-30 people using this how is he the first to hit it. It makes no sense...

**Comment by JesseRMeyer** [comment]
I tried rendering again with the column/row fix, but it still doesn't work for me.

There's some relevent information in the pictures below.
http://imgur.com/a/ek2yM

**Comment by bvisness** [comment]
Hmm. Could you maybe try a simpler case? Not sure which matrix might be the problem now.

**Comment by StrangeZak** [comment]
That wireframe looks right for the most part, at least i think

**Comment by StrangeZak** [comment]
Change your model matrix to:

`    hmm_mat4 ModelMatrix = HMM_Mat4d(1.0f);`

And see what happens?

**Comment by JesseRMeyer** [comment]
The wireframe is constructed by RenderDoc. You're supposed to see what you're rendering show up inside the bounds.

HMM_Mat4d(1.0f); didn't seem to do anything different. I'm relying on that being being an intrinsic part of the Translate function anyway.

Here's a gif of me 'building' up the final matrix. I'm out of time looking into this today, so I can either upload my project's source or after the weekend I can provide a simpler usage case.

http://imgur.com/elyx1Ux

**Comment by JesseRMeyer** [comment]
For reference it's supposed to look like this: http://imgur.com/Tqs8Ayb

**Comment by StrangeZak** [comment]
Ill relook at this issue after my stream tomorrow maybe it will shed some light on this situation

**Comment by StrangeZak** [comment]
Didnt mean to close this....

**Comment by StrangeZak** [comment]
@JesseRMeyer There should be a new major version coming in the next few days where we will fix various bugs then we will try this again. Sorry for the hassle there might be a few bugs that i am not aware of

**Comment by StrangeZak** [comment]
@JesseRMeyer Merged in a fix today, would be great if you could see if it fixes it for you. If not we will try again in a few days as there is a few bugs to squash

**Comment by bvisness** [comment]
@JesseRMeyer We just merged a bunch more changes across the whole library (which is now thoroughly unit tested!) Give it another try and let us know how it goes. 😄

**Comment by JesseRMeyer** [comment]
Awesome works guys. I'll test this soon and will report back.

**Comment by JesseRMeyer** [comment]
You magnificent bastards! http://imgur.com/a/1rig0

This really did act as a drop in replacement! The only difference so far is that HMM handles FOV slightly differently, so I had to change 45.0f to 90f for the perspective matrix. Very minor hurdle and obvious to track down. But you may want to make a mention of it for those wanting an absolutely easy transition.

**Comment by StrangeZak** [comment]
@bvisness Any idea what hes talking about for the FOV thing ?

**Comment by StrangeZak** [comment]
@JesseRMeyer Glad everything is working now :)

**Comment by bvisness** [comment]
GLM probably requires you to put in half the desired FOV (45.0f for a 90.0f total FOV.) The function we're using just divides it in half before doing the math. No big deal, we're not doing anything wrong, just a difference in what the functions expect.

**Comment by StrangeZak** [comment]
@bvisness Awesome, i think we can finally close this issue :+1:
