### ISSUE TITLE
SSE improvements

### ISSUE THREAD

**Issue by mmozeiko** [StrangeZak/Handmade-Math#23]
Don't do this:

    __m128 In = _mm_load_ss(&Value);
    __m128 Out = _mm_sqrt_ss(In);
    _mm_store_ss(&Result, Out);

Do this instead:

    __m128 In = _mm_set_ss(Value);
    __m128 Out = _mm_sqrt_ss(In);
    Result = _mm_cvtss_f32(Out);

load/store operations makes compiler to store float to memory (if it is not smart enough to optimize what is going on here), and that is bad. Because on x86_64 architecture floats arguments and result uses SSE register, so you are forcing Value to be first stored to memory for _mm_load_ss immediately afterwards to load it from memory. Similarly with Result - it is forced to be stored to memory with _mm_store_ss just load it afterwards for returning it.

set/cvtss operations generate single MOV instruction each (if needed at all). For x86_64 they won't generate any code at all because input argument already is in SSE register and result also need to be in SSE register.

And a bit unrelated comment to SEE - HMM_Power can be greatly improved by doing squaring algorithm: https://en.wikipedia.org/wiki/Exponentiation_by_squaring

**Comment by StrangeZak** [comment]
Thanks for the fix, and the suggestion mmozeiko, random unrelated question for you now. Do you think its worth it to SSE-ify all our Matrix and Vector operations?

**Comment by mmozeiko** [comment]
For some operations it can help a lot (like matrix-matrix or marix-vector multiplication). For other, probably no. Because typically you operate with 2d or 3d vector, but using those in SSE operations is awkward. Only 4d vector maps cleanly to SSE operations.

**Comment by StrangeZak** [comment]
Fixed the SSE issue in the most recent version
