### ISSUE TITLE
No matrix transpose function

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#28]
We do not have a function for transposing `hmm_mat4`s. Adding one seems like the responsible thing to do! Probably call it `HMM_Transpose(hmm_mat4 Matrix)`.

**Comment by StrangeZak** [comment]
What does a matrix Transpose function do?

**Comment by bvisness** [comment]
Transposing a matrix [swaps its rows and columns](https://chortle.ccsu.edu/VectorLessons/vmch13/vmch13_14.html)

**Comment by StrangeZak** [comment]
Heh if you know how to write one off the top of your head it'd be awesome if you could do it. If not then i will figure it out
