### ISSUE TITLE
HMM_Inner and HMM_Dot are redundant and limited

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#30]
`HMM_Inner` and `HMM_Dot` both perform exactly the same type of vector multiplication, and are thus redundant. However, only `HMM_Inner` is used internally.

In addition, both of these functions only support `hmm_vec3`. We should consider adding versions of this function for all three types of vectors.

**Comment by StrangeZak** [comment]
For sure this is a easy fix, i just know some people like to use inner and some people like to use dot, even though dot is correct. Should we just have Inner call dot, or just remove Inner entirely

**Comment by bvisness** [comment]
I would vote to remove inner.

**Comment by StrangeZak** [comment]
Inner will be gone in my next commit then

**Comment by StrangeZak** [comment]
All these bug fixes probably warrant a new major version right ?

**Comment by bvisness** [comment]
I would say so, yes.

**Comment by bvisness** [comment]
Fixed in #37.
