### ISSUE TITLE
HMM_LengthSquareRoot is poorly named

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#33]
This is not a bug, exactly, but when I was integrating Handmade Math into my project I was confused by the naming of `HMM_LengthSquareRoot`. I expected `HMM_LengthSquared`, or something, since the function actually produces the length of the vector squared. (No square root has happened yet!)

**Comment by StrangeZak** [comment]
Oh! That should be changed then!

**Comment by bvisness** [comment]
Changing the name has the potential to break projects though. Are we ok with that since we're still in early release, or would we want to mark it as deprecated somehow...? (I vote for just breaking things.)

**Comment by StrangeZak** [comment]
Were pre 1.0 were fine to break things as long as put a notice in that we broke something

**Comment by bvisness** [comment]
Fixed in #37.
