### ISSUE TITLE
Vec2i, Vec3i, Vec4i are unnecessary?

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#34]
What is the purpose of having `HMM_Vec2i`, `HMM_Vec3i`, and `HMM_Vec4i`? All three functions simply cast their integer arguments to floats. And there is no loss of precision when converting `int` to `float`, so compilers should be able to do this conversion implicitly in the float versions of these functions.

(This may just be my relative inexperience programming in plain old C.)

**Comment by StrangeZak** [comment]
So, i dont know if this is a good reason or not. MSVC gives a warning if you put int into a function that takes a float argument so it generates and if you used Vec2i for creating a vector of "ints" it will not generate a warning that way.

**Comment by StrangeZak** [comment]
So i kinda think that they are worth keeping just to keep the warning amount at a minimum

**Comment by bvisness** [comment]
Good enough reason for me! (MSVC sounds very frustrating though!)

**Comment by StrangeZak** [comment]
@bvisness It is im pumping out a lot of these bugs expect a commit within the next hour. Is the unit test up and running?

**Comment by bvisness** [comment]
Not on Travis yet, but I can run them locally and report back. (I'll look into the Travis config now that it's merged.)
