### ISSUE TITLE
The Road to 1.0

### ISSUE THREAD

**Issue by StrangeZak** [StrangeZak/Handmade-Math#43]
This isn't a issue at all, but i was just thinking, what do we need / what are we missing (besides testing) to be able to bring this thing into 1.0. I figured it was just good to open up a conversation over this,

I would love everybody s opinion on this :)

**Comment by bvisness** [comment]
Biggest thing that comes to mind is supporting operations across all data types. Like:
- `HMM_Length`, `HMM_LengthSquared`, `HMM_Cross`, and `HMM_Normalize` only support vec3 right now
- `HMM_Lerp` only support floats, not vectors (even though it totally could)

**Comment by bvisness** [comment]
There are probably a bunch of more obscure linear algebra applications we could go into, but that's probably way beyond the purpose and intent of this library.

**Comment by StrangeZak** [comment]
We dont handle NaN at all either. I dont know if its something we want to handle, or if its even worth our time. We had a conversation over it last night, ill post the thread here, but i was wonder what your opinion is on this.
![capture 3png](https://cloud.githubusercontent.com/assets/8273141/18138113/101cf530-6f60-11e6-96bc-4773cdae48f7.PNG)

**Comment by bvisness** [comment]
Well, I think Handmade Math is trying to be a good *graphics* math library, not necessarily a full library for math *in general*. For example, if we were trying to be general-purpose math, we would probably have arbitrarily sized vectors and matrices, both horizontal and vertical vectors, probably lots more obscure functions. But doing all that hurts performance and adds complexity for the more limited set of operations that are common in games and graphics.

I think no Handmade Math function should crash on bad input, but returning values like NaN is fine in my book. I do like the idea of having (perhaps optional) debug asserts for values for which a function is not defined.

**Comment by StrangeZak** [comment]
Yeah, im thinking we could just throw an assert if the function receives bad input

**Comment by StrangeZak** [comment]
@bvisness  I think you can only get the cross product between two vectors if the vector has 3 components. I dont have a linear algebra book laying around but i found this here when trying to do the upgrade: https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/linear-algebra-cross-product-introduction . I might just be being stupid but you can tell me if i am.

**Comment by bvisness** [comment]
No, looks like cross product only applies to 3-dimensional vectors. I forgot about that...

I quote from [Wikipedia](https://en.wikipedia.org/wiki/Cross_product):

> In mathematics and vector calculus, the cross product or vector product (occasionally directed area product to emphasize the geometric significance) is a binary operation on two vectors **in three-dimensional space (R3)** and is denoted by the symbol ×.

**Comment by StrangeZak** [comment]
@bvisness Man, you had me on a search for like 2 days trying to calculate a cross product of a R2 and R4 vector. Good to know its cleared up now, ill finish off the patch tonight.
