### ISSUE TITLE
Orthographics Matrix

### ISSUE THREAD

**Issue by StrangeZak** [StrangeZak/Handmade-Math#51]
This might just be me being stupid or me not doing something correct with OpenGL, but i think our Orthographics Matrix might be screwed can anyone with a working application throw a Orthographic matrix on their camera and see if anything is screwed up.

**Comment by StrangeZak** [comment]
@bvisness

**Comment by bvisness** [comment]
Works fine for me:

![image](https://cloud.githubusercontent.com/assets/4707402/22414521/b853c886-e685-11e6-86f2-7e23daf8ce61.png)

And hopefully our test should prove it's working. (Take a look at the example vector and what it gets projected to. Hopefully it should make sense.) https://github.com/StrangeZak/Handmade-Math/blob/master/test/hmm_test.cpp#L1662-L1673

**Comment by bvisness** [comment]
By the way, to test it, all I did was change my projection matrix to use HMM_Orthographic with sensible settings instead of HMM_Perspective. My model and view matrices remained the same.

**Comment by StrangeZak** [comment]
Dumb opengl bug last night forgot you gotta scale all sprites by the sprite size with a orthographic view, this is what happens when you go from 3d to 2d.
