### ISSUE TITLE
HMM_Quaternion(...), HMM_Length(hmm_vecx) not defined as inline?

### ISSUE THREAD

**Issue by in0x** [StrangeZak/Handmade-Math#55]
Is there a reason why these functions are not defined with inline? My first assumption is that this is simply a typo since the defintions have HMMDEF. If the header is included in multiple translation units, these functions not being declared inline can cause multiply defined symbols, which I just ran into.

**Comment by bvisness** [comment]
Whoops, that's a typo. Thanks for bringing that to our attention.
