### ISSUE TITLE
HANDMADE_MATH_CPP_MODE instructions?

### ISSUE THREAD

**Issue by nlguillemot** [StrangeZak/Handmade-Math#66]
The instructions for HANDMADE_MATH_CPP_MODE are as follows:

```
  For overloaded and operator overloaded versions of the base C functions,
  you MUST
  
     #define HANDMADE_MATH_CPP_MODE
     
  in EXACTLY one C or C++ file that includes this header, BEFORE the
  include, like this:
  
     #define HANDMADE_MATH_IMPLEMENTATION
     #define HANDMADE_MATH_CPP_MODE
     #include "HandmadeMath.h"
     
  All other files should just #include "HandmadeMath.h" without the #define.
```

By defining HANDMADE_MATH_CPP_MODE, HandmadeMath.h enables the following:
1. Declarations of overloaded functions
2. Declarations of operator overloads
3. Definitions of overloaded functions
4. Definitions of operator overloads

The documentation says other files should just include HandmadeMath.h without the #define, but if that's the case, those other files won't see the declarations of the functions. Either this doesn't work or there's something I don't understand.

**Comment by bvisness** [comment]
Yeah, I'm not sure about those instructions either. I've always just #defined HANDMADE_MATH_CPP_MODE everywhere I include it.

@StrangeZak, is it really possible to use C++ functions without defining HANDMADE_MATH_CPP_MODE everywhere? Is that just some very drastic difference between MSVC and other compilers?

**Comment by StrangeZak** [comment]
@bviness It shouldn't be possible to use C++ functions without defining HANDMADE_MATH_CPP_MODE. As i wrapped everything C++ in that define.

**Comment by StrangeZak** [comment]
Im not sure how we should handle this since most single-header libraries, don't really have a C++ mode in them.

**Comment by nlguillemot** [comment]
One solution is to always declare the C++ functions when `defined(__cplusplus)` is true. If you try to use them, you'll get a link error unless you also define HANDMADE_MATH_CPP_MODE. Maybe that's a decent compromise if somebody wants to have some compile-time check that they're not using the C++ interface. The downside is that the C++ declarations will show up in autocompletions and etc.

**Comment by bvisness** [comment]
Ok, so our two options are:
1. Correct the instructions to say that you must `#define HANDMADE_MATH_CPP_MODE` everywhere you include HandmadeMath.h
2. Remove `HANDMADE_MATH_CPP_MODE` and just include C++ content automatically.

I like option 2 since it makes things easier to implement, and no one is forced to use the C++ content anyway, but it's up to @StrangeZak to make the final call.

**Comment by StrangeZak** [comment]
Yeah, option 2 is probably the way to go. 👍
