### ISSUE TITLE
Gives errors regarding alignment in x86

### ISSUE THREAD

**Issue by msmshazan** [StrangeZak/Handmade-Math#69]
(same as title)

**Comment by kiljacken** [comment]
It would be helpful if you could attach the error messages you get. A vague description of the problem like this will not help in solving the issue.

What's your setup like (OS, Compiler, C/C++, etc.) and in what context does the error occur? :)

**Comment by StrangeZak** [comment]
Yep need some more info before i can fix this

**Comment by StrangeZak** [comment]
Closing this since we have not been given more info to fix this.
